# Auto-generated by 
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/ekutech/edk2-exynos
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/ekutech/edk2-exynos/Common/edk2/BaseTools
fi
if [ -e /home/ekutech/edk2-exynos/Common/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/ekutech/edk2-exynos/Common/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/ekutech/edk2-exynos/Common/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
